version: "3"
services:
  app:
    image: 163482350712.dkr.ecr.eu-west-1.amazonaws.com/unguess-api:${BRANCH}
    restart: always
    env_file:
      - ./.env
    ports:
      - "${PORT:-80}:80"
    environment:
      - PORT=80