import KnexMigrations from "./tryber/KnexMigrations";
import KnexMigrationsLock from "./tryber/KnexMigrationsLock";
import WpAddactionsandfiltersPluginUsercode from "./tryber/WpAddactionsandfiltersPluginUsercode";
import WpAppqActivityLevel from "./tryber/WpAppqActivityLevel";
import WpAppqActivityLevelDefinition from "./tryber/WpAppqActivityLevelDefinition";
import WpAppqActivityLevelRev from "./tryber/WpAppqActivityLevelRev";
import WpAppqAdditionalBugReplicabilities from "./tryber/WpAppqAdditionalBugReplicabilities";
import WpAppqAdditionalBugSeverities from "./tryber/WpAppqAdditionalBugSeverities";
import WpAppqAdditionalBugTypes from "./tryber/WpAppqAdditionalBugTypes";
import WpAppqAdminCommunication from "./tryber/WpAppqAdminCommunication";
import WpAppqAdminEmail from "./tryber/WpAppqAdminEmail";
import WpAppqBugLink from "./tryber/WpAppqBugLink";
import WpAppqBugReadStatus from "./tryber/WpAppqBugReadStatus";
import WpAppqBugTaxonomy from "./tryber/WpAppqBugTaxonomy";
import WpAppqCampaignAdditionalFields from "./tryber/WpAppqCampaignAdditionalFields";
import WpAppqCampaignAdditionalFieldsData from "./tryber/WpAppqCampaignAdditionalFieldsData";
import WpAppqCampaignCategory from "./tryber/WpAppqCampaignCategory";
import WpAppqCampaignClassificationClass from "./tryber/WpAppqCampaignClassificationClass";
import WpAppqCampaignClassificationFamily from "./tryber/WpAppqCampaignClassificationFamily";
import WpAppqCampaignClassificationStatus from "./tryber/WpAppqCampaignClassificationStatus";
import WpAppqCampaignPageTemplate from "./tryber/WpAppqCampaignPageTemplate";
import WpAppqCampaignPageTemplatePart from "./tryber/WpAppqCampaignPageTemplatePart";
import WpAppqCampaignPageTemplatePartData from "./tryber/WpAppqCampaignPageTemplatePartData";
import WpAppqCampaignPreselectionForm from "./tryber/WpAppqCampaignPreselectionForm";
import WpAppqCampaignPreselectionFormData from "./tryber/WpAppqCampaignPreselectionFormData";
import WpAppqCampaignPreselectionFormFields from "./tryber/WpAppqCampaignPreselectionFormFields";
import WpAppqCampaignStatus from "./tryber/WpAppqCampaignStatus";
import WpAppqCampaignTask from "./tryber/WpAppqCampaignTask";
import WpAppqCampaignTaskGroup from "./tryber/WpAppqCampaignTaskGroup";
import WpAppqCampaignType from "./tryber/WpAppqCampaignType";
import WpAppqCampaignUseCaseTemplates from "./tryber/WpAppqCampaignUseCaseTemplates";
import WpAppqCampaignUserPermissions from "./tryber/WpAppqCampaignUserPermissions";
import WpAppqCertificationsList from "./tryber/WpAppqCertificationsList";
import WpAppqClickDayCode from "./tryber/WpAppqClickDayCode";
import WpAppqClickDayResult from "./tryber/WpAppqClickDayResult";
import WpAppqClickDaySetup from "./tryber/WpAppqClickDaySetup";
import WpAppqCompletedTutorial from "./tryber/WpAppqCompletedTutorial";
import WpAppqContracts from "./tryber/WpAppqContracts";
import WpAppqCourse from "./tryber/WpAppqCourse";
import WpAppqCourseAnswer from "./tryber/WpAppqCourseAnswer";
import WpAppqCourseLesson from "./tryber/WpAppqCourseLesson";
import WpAppqCourseQuestion from "./tryber/WpAppqCourseQuestion";
import WpAppqCourseTesterAnswer from "./tryber/WpAppqCourseTesterAnswer";
import WpAppqCourseTesterAnswerRev from "./tryber/WpAppqCourseTesterAnswerRev";
import WpAppqCourseTesterCertification from "./tryber/WpAppqCourseTesterCertification";
import WpAppqCourseTesterStatus from "./tryber/WpAppqCourseTesterStatus";
import WpAppqCpMeta from "./tryber/WpAppqCpMeta";
import WpAppqCpTestbook from "./tryber/WpAppqCpTestbook";
import WpAppqCpTestbookStatus from "./tryber/WpAppqCpTestbookStatus";
import WpAppqCpTestbookStep from "./tryber/WpAppqCpTestbookStep";
import WpAppqCronJobs from "./tryber/WpAppqCronJobs";
import WpAppqCustomUserField from "./tryber/WpAppqCustomUserField";
import WpAppqCustomUserFieldData from "./tryber/WpAppqCustomUserFieldData";
import WpAppqCustomUserFieldDependencies from "./tryber/WpAppqCustomUserFieldDependencies";
import WpAppqCustomUserFieldExtras from "./tryber/WpAppqCustomUserFieldExtras";
import WpAppqCustomUserFieldGroupTranslation from "./tryber/WpAppqCustomUserFieldGroupTranslation";
import WpAppqCustomUserFieldGroups from "./tryber/WpAppqCustomUserFieldGroups";
import WpAppqCustomUserFieldTranslation from "./tryber/WpAppqCustomUserFieldTranslation";
import WpAppqCustomer from "./tryber/WpAppqCustomer";
import WpAppqCustomerAccountInvitations from "./tryber/WpAppqCustomerAccountInvitations";
import WpAppqEducation from "./tryber/WpAppqEducation";
import WpAppqEmployment from "./tryber/WpAppqEmployment";
import WpAppqEvdBug from "./tryber/WpAppqEvdBug";
import WpAppqEvdBugMedia from "./tryber/WpAppqEvdBugMedia";
import WpAppqEvdBugReplicability from "./tryber/WpAppqEvdBugReplicability";
import WpAppqEvdBugRev from "./tryber/WpAppqEvdBugRev";
import WpAppqEvdBugStatus from "./tryber/WpAppqEvdBugStatus";
import WpAppqEvdBugType from "./tryber/WpAppqEvdBugType";
import WpAppqEvdCampaign from "./tryber/WpAppqEvdCampaign";
import WpAppqEvdCampaignRev from "./tryber/WpAppqEvdCampaignRev";
import WpAppqEvdPlatform from "./tryber/WpAppqEvdPlatform";
import WpAppqEvdProfile from "./tryber/WpAppqEvdProfile";
import WpAppqEvdSeverity from "./tryber/WpAppqEvdSeverity";
import WpAppqEvent from "./tryber/WpAppqEvent";
import WpAppqEventTransactionalMail from "./tryber/WpAppqEventTransactionalMail";
import WpAppqExpPoints from "./tryber/WpAppqExpPoints";
import WpAppqFiscalProfile from "./tryber/WpAppqFiscalProfile";
import WpAppqIntegrationCenterBugs from "./tryber/WpAppqIntegrationCenterBugs";
import WpAppqIntegrationCenterConfig from "./tryber/WpAppqIntegrationCenterConfig";
import WpAppqIntegrationCenterCustomMap from "./tryber/WpAppqIntegrationCenterCustomMap";
import WpAppqIntegrationCenterIntegrations from "./tryber/WpAppqIntegrationCenterIntegrations";
import WpAppqLang from "./tryber/WpAppqLang";
import WpAppqLcAccess from "./tryber/WpAppqLcAccess";
import WpAppqLcManufacturer from "./tryber/WpAppqLcManufacturer";
import WpAppqLcMessages from "./tryber/WpAppqLcMessages";
import WpAppqLcModel from "./tryber/WpAppqLcModel";
import WpAppqLcNetwork from "./tryber/WpAppqLcNetwork";
import WpAppqLcTasks from "./tryber/WpAppqLcTasks";
import WpAppqLcViewMeta from "./tryber/WpAppqLcViewMeta";
import WpAppqMiRequest from "./tryber/WpAppqMiRequest";
import WpAppqOlpPermissions from "./tryber/WpAppqOlpPermissions";
import WpAppqOs from "./tryber/WpAppqOs";
import WpAppqPayment from "./tryber/WpAppqPayment";
import WpAppqPaymentRequest from "./tryber/WpAppqPaymentRequest";
import WpAppqPaymentRequestHistory from "./tryber/WpAppqPaymentRequestHistory";
import WpAppqPaymentTwQuote from "./tryber/WpAppqPaymentTwQuote";
import WpAppqPaymentTwRecipient from "./tryber/WpAppqPaymentTwRecipient";
import WpAppqPaymentTwTransfer from "./tryber/WpAppqPaymentTwTransfer";
import WpAppqPaymentWorkTypes from "./tryber/WpAppqPaymentWorkTypes";
import WpAppqPaypalBulkTransaction from "./tryber/WpAppqPaypalBulkTransaction";
import WpAppqPaypalTransaction from "./tryber/WpAppqPaypalTransaction";
import WpAppqPlatform from "./tryber/WpAppqPlatform";
import WpAppqPopups from "./tryber/WpAppqPopups";
import WpAppqPopupsReadStatus from "./tryber/WpAppqPopupsReadStatus";
import WpAppqProfileCertifications from "./tryber/WpAppqProfileCertifications";
import WpAppqProfileEditTimestamp from "./tryber/WpAppqProfileEditTimestamp";
import WpAppqProfileHasLang from "./tryber/WpAppqProfileHasLang";
import WpAppqProfileSkills from "./tryber/WpAppqProfileSkills";
import WpAppqProfileSkillsSrc from "./tryber/WpAppqProfileSkillsSrc";
import WpAppqProject from "./tryber/WpAppqProject";
import WpAppqProspectPayout from "./tryber/WpAppqProspectPayout";
import WpAppqQualityBadge from "./tryber/WpAppqQualityBadge";
import WpAppqReceipt from "./tryber/WpAppqReceipt";
import WpAppqReferralData from "./tryber/WpAppqReferralData";
import WpAppqReport from "./tryber/WpAppqReport";
import WpAppqStatusReasonText from "./tryber/WpAppqStatusReasonText";
import WpAppqStatusReasonUsage from "./tryber/WpAppqStatusReasonUsage";
import WpAppqTaskAdditionalData from "./tryber/WpAppqTaskAdditionalData";
import WpAppqTesterJotformSubmissions from "./tryber/WpAppqTesterJotformSubmissions";
import WpAppqTicket from "./tryber/WpAppqTicket";
import WpAppqUnlayerBlockTemplate from "./tryber/WpAppqUnlayerBlockTemplate";
import WpAppqUnlayerCategory from "./tryber/WpAppqUnlayerCategory";
import WpAppqUnlayerMailTemplate from "./tryber/WpAppqUnlayerMailTemplate";
import WpAppqUploadedMedia from "./tryber/WpAppqUploadedMedia";
import WpAppqUsecaseCluster from "./tryber/WpAppqUsecaseCluster";
import WpAppqUsecaseMediaObservations from "./tryber/WpAppqUsecaseMediaObservations";
import WpAppqUsecaseMediaObservationsTags from "./tryber/WpAppqUsecaseMediaObservationsTags";
import WpAppqUsecaseMediaObservationsTagsLink from "./tryber/WpAppqUsecaseMediaObservationsTagsLink";
import WpAppqUsecaseMediaReadStatus from "./tryber/WpAppqUsecaseMediaReadStatus";
import WpAppqUsecaseMediaShare from "./tryber/WpAppqUsecaseMediaShare";
import WpAppqUsecaseMediaTagType from "./tryber/WpAppqUsecaseMediaTagType";
import WpAppqUserDeletionReason from "./tryber/WpAppqUserDeletionReason";
import WpAppqUserTask from "./tryber/WpAppqUserTask";
import WpAppqUserTaskMedia from "./tryber/WpAppqUserTaskMedia";
import WpAppqUserToCustomer from "./tryber/WpAppqUserToCustomer";
import WpAppqUserToProject from "./tryber/WpAppqUserToProject";
import WpCdTestQuestion from "./tryber/WpCdTestQuestion";
import WpCdTestResults from "./tryber/WpCdTestResults";
import WpCommentmeta from "./tryber/WpCommentmeta";
import WpComments from "./tryber/WpComments";
import WpCrowdAppqDevice from "./tryber/WpCrowdAppqDevice";
import WpCrowdAppqHasCandidate from "./tryber/WpCrowdAppqHasCandidate";
import WpDcAppqAcceptedProperties from "./tryber/WpDcAppqAcceptedProperties";
import WpDcAppqApiHaveScope from "./tryber/WpDcAppqApiHaveScope";
import WpDcAppqApiKeys from "./tryber/WpDcAppqApiKeys";
import WpDcAppqApiScopes from "./tryber/WpDcAppqApiScopes";
import WpDcAppqConnectorSettings from "./tryber/WpDcAppqConnectorSettings";
import WpDcAppqDevices from "./tryber/WpDcAppqDevices";
import WpDcAppqPluginSync from "./tryber/WpDcAppqPluginSync";
import WpFormsApplication from "./tryber/WpFormsApplication";
import WpLinks from "./tryber/WpLinks";
import WpOptions from "./tryber/WpOptions";
import WpPostmeta from "./tryber/WpPostmeta";
import WpPosts from "./tryber/WpPosts";
import WpRedirection404 from "./tryber/WpRedirection404";
import WpRedirectionGroups from "./tryber/WpRedirectionGroups";
import WpRedirectionItems from "./tryber/WpRedirectionItems";
import WpRedirectionLogs from "./tryber/WpRedirectionLogs";
import WpSignups from "./tryber/WpSignups";
import WpTermRelationships from "./tryber/WpTermRelationships";
import WpTermTaxonomy from "./tryber/WpTermTaxonomy";
import WpTermmeta from "./tryber/WpTermmeta";
import WpTerms from "./tryber/WpTerms";
import WpUsermeta from "./tryber/WpUsermeta";
import WpUsers from "./tryber/WpUsers";
import WpWpmmSubscribers from "./tryber/WpWpmmSubscribers";

export const create = async () => {
  await KnexMigrations.create();
  await KnexMigrationsLock.create();
  await WpAddactionsandfiltersPluginUsercode.create();
  await WpAppqActivityLevel.create();
  await WpAppqActivityLevelDefinition.create();
  await WpAppqActivityLevelRev.create();
  await WpAppqAdditionalBugReplicabilities.create();
  await WpAppqAdditionalBugSeverities.create();
  await WpAppqAdditionalBugTypes.create();
  await WpAppqAdminCommunication.create();
  await WpAppqAdminEmail.create();
  await WpAppqBugLink.create();
  await WpAppqBugReadStatus.create();
  await WpAppqBugTaxonomy.create();
  await WpAppqCampaignAdditionalFields.create();
  await WpAppqCampaignAdditionalFieldsData.create();
  await WpAppqCampaignCategory.create();
  await WpAppqCampaignClassificationClass.create();
  await WpAppqCampaignClassificationFamily.create();
  await WpAppqCampaignClassificationStatus.create();
  await WpAppqCampaignPageTemplate.create();
  await WpAppqCampaignPageTemplatePart.create();
  await WpAppqCampaignPageTemplatePartData.create();
  await WpAppqCampaignPreselectionForm.create();
  await WpAppqCampaignPreselectionFormData.create();
  await WpAppqCampaignPreselectionFormFields.create();
  await WpAppqCampaignStatus.create();
  await WpAppqCampaignTask.create();
  await WpAppqCampaignTaskGroup.create();
  await WpAppqCampaignType.create();
  await WpAppqCampaignUseCaseTemplates.create();
  await WpAppqCampaignUserPermissions.create();
  await WpAppqCertificationsList.create();
  await WpAppqClickDayCode.create();
  await WpAppqClickDayResult.create();
  await WpAppqClickDaySetup.create();
  await WpAppqCompletedTutorial.create();
  await WpAppqContracts.create();
  await WpAppqCourse.create();
  await WpAppqCourseAnswer.create();
  await WpAppqCourseLesson.create();
  await WpAppqCourseQuestion.create();
  await WpAppqCourseTesterAnswer.create();
  await WpAppqCourseTesterAnswerRev.create();
  await WpAppqCourseTesterCertification.create();
  await WpAppqCourseTesterStatus.create();
  await WpAppqCpMeta.create();
  await WpAppqCpTestbook.create();
  await WpAppqCpTestbookStatus.create();
  await WpAppqCpTestbookStep.create();
  await WpAppqCronJobs.create();
  await WpAppqCustomUserField.create();
  await WpAppqCustomUserFieldData.create();
  await WpAppqCustomUserFieldDependencies.create();
  await WpAppqCustomUserFieldExtras.create();
  await WpAppqCustomUserFieldGroupTranslation.create();
  await WpAppqCustomUserFieldGroups.create();
  await WpAppqCustomUserFieldTranslation.create();
  await WpAppqCustomer.create();
  await WpAppqCustomerAccountInvitations.create();
  await WpAppqEducation.create();
  await WpAppqEmployment.create();
  await WpAppqEvdBug.create();
  await WpAppqEvdBugMedia.create();
  await WpAppqEvdBugReplicability.create();
  await WpAppqEvdBugRev.create();
  await WpAppqEvdBugStatus.create();
  await WpAppqEvdBugType.create();
  await WpAppqEvdCampaign.create();
  await WpAppqEvdCampaignRev.create();
  await WpAppqEvdPlatform.create();
  await WpAppqEvdProfile.create();
  await WpAppqEvdSeverity.create();
  await WpAppqEvent.create();
  await WpAppqEventTransactionalMail.create();
  await WpAppqExpPoints.create();
  await WpAppqFiscalProfile.create();
  await WpAppqIntegrationCenterBugs.create();
  await WpAppqIntegrationCenterConfig.create();
  await WpAppqIntegrationCenterCustomMap.create();
  await WpAppqIntegrationCenterIntegrations.create();
  await WpAppqLang.create();
  await WpAppqLcAccess.create();
  await WpAppqLcManufacturer.create();
  await WpAppqLcMessages.create();
  await WpAppqLcModel.create();
  await WpAppqLcNetwork.create();
  await WpAppqLcTasks.create();
  await WpAppqLcViewMeta.create();
  await WpAppqMiRequest.create();
  await WpAppqOlpPermissions.create();
  await WpAppqOs.create();
  await WpAppqPayment.create();
  await WpAppqPaymentRequest.create();
  await WpAppqPaymentRequestHistory.create();
  await WpAppqPaymentTwQuote.create();
  await WpAppqPaymentTwRecipient.create();
  await WpAppqPaymentTwTransfer.create();
  await WpAppqPaymentWorkTypes.create();
  await WpAppqPaypalBulkTransaction.create();
  await WpAppqPaypalTransaction.create();
  await WpAppqPlatform.create();
  await WpAppqPopups.create();
  await WpAppqPopupsReadStatus.create();
  await WpAppqProfileCertifications.create();
  await WpAppqProfileEditTimestamp.create();
  await WpAppqProfileHasLang.create();
  await WpAppqProfileSkills.create();
  await WpAppqProfileSkillsSrc.create();
  await WpAppqProject.create();
  await WpAppqProspectPayout.create();
  await WpAppqQualityBadge.create();
  await WpAppqReceipt.create();
  await WpAppqReferralData.create();
  await WpAppqReport.create();
  await WpAppqStatusReasonText.create();
  await WpAppqStatusReasonUsage.create();
  await WpAppqTaskAdditionalData.create();
  await WpAppqTesterJotformSubmissions.create();
  await WpAppqTicket.create();
  await WpAppqUnlayerBlockTemplate.create();
  await WpAppqUnlayerCategory.create();
  await WpAppqUnlayerMailTemplate.create();
  await WpAppqUploadedMedia.create();
  await WpAppqUsecaseCluster.create();
  await WpAppqUsecaseMediaObservations.create();
  await WpAppqUsecaseMediaObservationsTags.create();
  await WpAppqUsecaseMediaObservationsTagsLink.create();
  await WpAppqUsecaseMediaReadStatus.create();
  await WpAppqUsecaseMediaShare.create();
  await WpAppqUsecaseMediaTagType.create();
  await WpAppqUserDeletionReason.create();
  await WpAppqUserTask.create();
  await WpAppqUserTaskMedia.create();
  await WpAppqUserToCustomer.create();
  await WpAppqUserToProject.create();
  await WpCdTestQuestion.create();
  await WpCdTestResults.create();
  await WpCommentmeta.create();
  await WpComments.create();
  await WpCrowdAppqDevice.create();
  await WpCrowdAppqHasCandidate.create();
  await WpDcAppqAcceptedProperties.create();
  await WpDcAppqApiHaveScope.create();
  await WpDcAppqApiKeys.create();
  await WpDcAppqApiScopes.create();
  await WpDcAppqConnectorSettings.create();
  await WpDcAppqDevices.create();
  await WpDcAppqPluginSync.create();
  await WpFormsApplication.create();
  await WpLinks.create();
  await WpOptions.create();
  await WpPostmeta.create();
  await WpPosts.create();
  await WpRedirection404.create();
  await WpRedirectionGroups.create();
  await WpRedirectionItems.create();
  await WpRedirectionLogs.create();
  await WpSignups.create();
  await WpTermRelationships.create();
  await WpTermTaxonomy.create();
  await WpTermmeta.create();
  await WpTerms.create();
  await WpUsermeta.create();
  await WpUsers.create();
  await WpWpmmSubscribers.create();
};
export const drop = async () => {
  await KnexMigrations.drop();
  await KnexMigrationsLock.drop();
  await WpAddactionsandfiltersPluginUsercode.drop();
  await WpAppqActivityLevel.drop();
  await WpAppqActivityLevelDefinition.drop();
  await WpAppqActivityLevelRev.drop();
  await WpAppqAdditionalBugReplicabilities.drop();
  await WpAppqAdditionalBugSeverities.drop();
  await WpAppqAdditionalBugTypes.drop();
  await WpAppqAdminCommunication.drop();
  await WpAppqAdminEmail.drop();
  await WpAppqBugLink.drop();
  await WpAppqBugReadStatus.drop();
  await WpAppqBugTaxonomy.drop();
  await WpAppqCampaignAdditionalFields.drop();
  await WpAppqCampaignAdditionalFieldsData.drop();
  await WpAppqCampaignCategory.drop();
  await WpAppqCampaignClassificationClass.drop();
  await WpAppqCampaignClassificationFamily.drop();
  await WpAppqCampaignClassificationStatus.drop();
  await WpAppqCampaignPageTemplate.drop();
  await WpAppqCampaignPageTemplatePart.drop();
  await WpAppqCampaignPageTemplatePartData.drop();
  await WpAppqCampaignPreselectionForm.drop();
  await WpAppqCampaignPreselectionFormData.drop();
  await WpAppqCampaignPreselectionFormFields.drop();
  await WpAppqCampaignStatus.drop();
  await WpAppqCampaignTask.drop();
  await WpAppqCampaignTaskGroup.drop();
  await WpAppqCampaignType.drop();
  await WpAppqCampaignUseCaseTemplates.drop();
  await WpAppqCampaignUserPermissions.drop();
  await WpAppqCertificationsList.drop();
  await WpAppqClickDayCode.drop();
  await WpAppqClickDayResult.drop();
  await WpAppqClickDaySetup.drop();
  await WpAppqCompletedTutorial.drop();
  await WpAppqContracts.drop();
  await WpAppqCourse.drop();
  await WpAppqCourseAnswer.drop();
  await WpAppqCourseLesson.drop();
  await WpAppqCourseQuestion.drop();
  await WpAppqCourseTesterAnswer.drop();
  await WpAppqCourseTesterAnswerRev.drop();
  await WpAppqCourseTesterCertification.drop();
  await WpAppqCourseTesterStatus.drop();
  await WpAppqCpMeta.drop();
  await WpAppqCpTestbook.drop();
  await WpAppqCpTestbookStatus.drop();
  await WpAppqCpTestbookStep.drop();
  await WpAppqCronJobs.drop();
  await WpAppqCustomUserField.drop();
  await WpAppqCustomUserFieldData.drop();
  await WpAppqCustomUserFieldDependencies.drop();
  await WpAppqCustomUserFieldExtras.drop();
  await WpAppqCustomUserFieldGroupTranslation.drop();
  await WpAppqCustomUserFieldGroups.drop();
  await WpAppqCustomUserFieldTranslation.drop();
  await WpAppqCustomer.drop();
  await WpAppqCustomerAccountInvitations.drop();
  await WpAppqEducation.drop();
  await WpAppqEmployment.drop();
  await WpAppqEvdBug.drop();
  await WpAppqEvdBugMedia.drop();
  await WpAppqEvdBugReplicability.drop();
  await WpAppqEvdBugRev.drop();
  await WpAppqEvdBugStatus.drop();
  await WpAppqEvdBugType.drop();
  await WpAppqEvdCampaign.drop();
  await WpAppqEvdCampaignRev.drop();
  await WpAppqEvdPlatform.drop();
  await WpAppqEvdProfile.drop();
  await WpAppqEvdSeverity.drop();
  await WpAppqEvent.drop();
  await WpAppqEventTransactionalMail.drop();
  await WpAppqExpPoints.drop();
  await WpAppqFiscalProfile.drop();
  await WpAppqIntegrationCenterBugs.drop();
  await WpAppqIntegrationCenterConfig.drop();
  await WpAppqIntegrationCenterCustomMap.drop();
  await WpAppqIntegrationCenterIntegrations.drop();
  await WpAppqLang.drop();
  await WpAppqLcAccess.drop();
  await WpAppqLcManufacturer.drop();
  await WpAppqLcMessages.drop();
  await WpAppqLcModel.drop();
  await WpAppqLcNetwork.drop();
  await WpAppqLcTasks.drop();
  await WpAppqLcViewMeta.drop();
  await WpAppqMiRequest.drop();
  await WpAppqOlpPermissions.drop();
  await WpAppqOs.drop();
  await WpAppqPayment.drop();
  await WpAppqPaymentRequest.drop();
  await WpAppqPaymentRequestHistory.drop();
  await WpAppqPaymentTwQuote.drop();
  await WpAppqPaymentTwRecipient.drop();
  await WpAppqPaymentTwTransfer.drop();
  await WpAppqPaymentWorkTypes.drop();
  await WpAppqPaypalBulkTransaction.drop();
  await WpAppqPaypalTransaction.drop();
  await WpAppqPlatform.drop();
  await WpAppqPopups.drop();
  await WpAppqPopupsReadStatus.drop();
  await WpAppqProfileCertifications.drop();
  await WpAppqProfileEditTimestamp.drop();
  await WpAppqProfileHasLang.drop();
  await WpAppqProfileSkills.drop();
  await WpAppqProfileSkillsSrc.drop();
  await WpAppqProject.drop();
  await WpAppqProspectPayout.drop();
  await WpAppqQualityBadge.drop();
  await WpAppqReceipt.drop();
  await WpAppqReferralData.drop();
  await WpAppqReport.drop();
  await WpAppqStatusReasonText.drop();
  await WpAppqStatusReasonUsage.drop();
  await WpAppqTaskAdditionalData.drop();
  await WpAppqTesterJotformSubmissions.drop();
  await WpAppqTicket.drop();
  await WpAppqUnlayerBlockTemplate.drop();
  await WpAppqUnlayerCategory.drop();
  await WpAppqUnlayerMailTemplate.drop();
  await WpAppqUploadedMedia.drop();
  await WpAppqUsecaseCluster.drop();
  await WpAppqUsecaseMediaObservations.drop();
  await WpAppqUsecaseMediaObservationsTags.drop();
  await WpAppqUsecaseMediaObservationsTagsLink.drop();
  await WpAppqUsecaseMediaReadStatus.drop();
  await WpAppqUsecaseMediaShare.drop();
  await WpAppqUsecaseMediaTagType.drop();
  await WpAppqUserDeletionReason.drop();
  await WpAppqUserTask.drop();
  await WpAppqUserTaskMedia.drop();
  await WpAppqUserToCustomer.drop();
  await WpAppqUserToProject.drop();
  await WpCdTestQuestion.drop();
  await WpCdTestResults.drop();
  await WpCommentmeta.drop();
  await WpComments.drop();
  await WpCrowdAppqDevice.drop();
  await WpCrowdAppqHasCandidate.drop();
  await WpDcAppqAcceptedProperties.drop();
  await WpDcAppqApiHaveScope.drop();
  await WpDcAppqApiKeys.drop();
  await WpDcAppqApiScopes.drop();
  await WpDcAppqConnectorSettings.drop();
  await WpDcAppqDevices.drop();
  await WpDcAppqPluginSync.drop();
  await WpFormsApplication.drop();
  await WpLinks.drop();
  await WpOptions.drop();
  await WpPostmeta.drop();
  await WpPosts.drop();
  await WpRedirection404.drop();
  await WpRedirectionGroups.drop();
  await WpRedirectionItems.drop();
  await WpRedirectionLogs.drop();
  await WpSignups.drop();
  await WpTermRelationships.drop();
  await WpTermTaxonomy.drop();
  await WpTermmeta.drop();
  await WpTerms.drop();
  await WpUsermeta.drop();
  await WpUsers.drop();
  await WpWpmmSubscribers.drop();
};
