name: 'Generate test coverage'
on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
      - name: 'Generate Coverage'
        run: |
          yarn coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
