name: "Generate test coverage"
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          yarn --frozen-lockfile
      - name: "Generate Coverage"
        run: |
          yarn coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
